Calender/Pages/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Calender.DBAccess;
using Calender.Models;

namespace Calender.Pages
{
    public class CreateModel : PageModel
    {
        private readonly Calender.DBAccess.DBAccessContext _context;

        public CreateModel(Calender.DBAccess.DBAccessContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public TaskInfo TaskInfo { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.DBAccess.Add(TaskInfo);
            await _context.SaveChangesAsync();

            return RedirectToPage("./TaskList");
        }
    }
}

Calender/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Calender.DBAccess;
using Calender.Models;

namespace Calender.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly Calender.DBAccess.DBAccessContext _context;

        public DeleteModel(Calender.DBAccess.DBAccessContext context)
        {
            _context = context;
        }

        [BindProperty]
        public TaskInfo TaskInfo { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TaskInfo = await _context.DBAccess.FirstOrDefaultAsync(m => m.ID == id);

            if (TaskInfo == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TaskInfo = await _context.DBAccess.FindAsync(id);

            if (TaskInfo != null)
            {
                _context.DBAccess.Remove(TaskInfo);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./TaskList");
        }
    }
}

Calender/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Calender.DBAccess;
using Calender.Models;

namespace Calender.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly Calender.DBAccess.DBAccessContext _context;

        public DetailsModel(Calender.DBAccess.DBAccessContext context)
        {
            _context = context;
        }

        public TaskInfo TaskInfo { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TaskInfo = await _context.DBAccess.FirstOrDefaultAsync(m => m.ID == id);

            if (TaskInfo == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Calender/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Calender.DBAccess;
using Calender.Models;

namespace Calender.Pages
{
    public class EditModel : PageModel
    {
        private readonly Calender.DBAccess.DBAccessContext _context;

        public EditModel(Calender.DBAccess.DBAccessContext context)
        {
            _context = context;
        }

        [BindProperty]
        public TaskInfo TaskInfo { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TaskInfo = await _context.DBAccess.FirstOrDefaultAsync(m => m.ID == id);

            if (TaskInfo == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(TaskInfo).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TaskInfoExists(TaskInfo.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./TaskList");
        }

        private bool TaskInfoExists(int id)
        {
            return _context.DBAccess.Any(e => e.ID == id);
        }
    }
}

Calender/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Calender.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Calender/Pages/Index.cshtml.cs
using Calender.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Calender.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public string Message { get; set; }
        public DateTime DayStart { get; set; }
        public DateTime ThisMonth { get; set; }
        public DateTime DispMonth { get; set; }
        public int[] Month { get; set; }
        private int MonthCount = 42;

        [BindProperty]
        public MonthInfo monthInfo { get; set; }

        public void OnGet()
        {
            DispMonth = System.DateTime.Now;
            int MonthLastDay = DateTime.DaysInMonth(DispMonth.Year, DispMonth.Month);
            Message = DispMonth.Year + "年" + DispMonth.Month + "月";
            DayStart = new DateTime(DispMonth.Year, DispMonth.Month, 1);
            Month = new int[MonthCount];
            Month = SetCalenderValue(DayStart);
        }

        public void OnGetPrevMonth(string prevMonth)
        {
            ThisMonth = DateTime.Parse(prevMonth).AddMonths(-1);
            DispMonth = new DateTime(ThisMonth.Year, ThisMonth.Month, 1);
            int MonthLastDay = DateTime.DaysInMonth(DispMonth.Year, DispMonth.Month);
            Message = DispMonth.Year + "年" + DispMonth.Month + "月";
            Month = new int[MonthCount];
            Month = SetCalenderValue(DispMonth);
        }


        public void OnGetNextMonth(string nextMonth)
        {
            ThisMonth = DateTime.Parse(nextMonth).AddMonths(1);
            DispMonth = new DateTime(ThisMonth.Year, ThisMonth.Month, 1);
            int MonthLastDay = DateTime.DaysInMonth(DispMonth.Year, DispMonth.Month);
            Message = DispMonth.Year + "年" + DispMonth.Month + "月";
            Month = SetCalenderValue(DispMonth);
        }

        public IActionResult OnPostPrev()
        {
            return RedirectToPage("/Index", "prevmonth", new { prevMonth = monthInfo.prevMonth });
        }
        public IActionResult OnPostNext()
        {
            return RedirectToPage("/Index", "nextmonth", new { nextMonth = monthInfo.nextMonth });
        }
        public IActionResult OnPostTasks()
        {
            return RedirectToPage("/TaskList", new { thisMonth = monthInfo.thisMonth, thisDay = monthInfo.thisDay });
        }


        private int[] SetCalenderValue(DateTime dispMonth)
        {
            int Difference = -1;
            Month = new int[MonthCount];
            int MonthLastDay = DateTime.DaysInMonth(dispMonth.Year, dispMonth.Month);

            for (int i = 0; i < MonthCount; i++)
            {
                if (i < (int)dispMonth.DayOfWeek)
                {
                    Month[i] = 0;
                    Difference++;
                }
                else if (i - Difference <= MonthLastDay)
                {
                    Month[i] = i - Difference;
                }
                else
                {
                    Month[i] = 0;
                }
            }
            return Month;
        }
    }
}

Calender/Pages/TaskList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Calender.DBAccess;
using Calender.Models;

namespace Calender.Pages
{
    public class TaskListModel : PageModel
    {
        private readonly Calender.DBAccess.DBAccessContext _context;

        public TaskListModel(Calender.DBAccess.DBAccessContext context)
        {
            _context = context;
        }

        public IList<TaskInfo> TaskInfo { get;set; }

        public async Task OnGetAsync()
        {
            TaskInfo = await _context.DBAccess.ToListAsync();
        }
    }
}

Calender/Pages/Tasks.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Calender.Pages
{
    public class TasksModel : PageModel
    {
        public DateTime DateValue { get; set; }
        public void OnGet(DateTime thisMonth, string thisDay)
        {
            DateValue = new DateTime(thisMonth.Year, thisMonth.Month, Int32.Parse(thisDay));
        }
    }
}

Calender/Pages/Create.cshtml
@page
@model Calender.Pages.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TaskInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TaskInfo.taskName" class="control-label"></label>
                <input asp-for="TaskInfo.taskName" class="form-control" />
                <span asp-validation-for="TaskInfo.taskName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskInfo.taskContents" class="control-label"></label>
                <input asp-for="TaskInfo.taskContents" class="form-control" />
                <span asp-validation-for="TaskInfo.taskContents" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskInfo.taskDate" class="control-label"></label>
                <input asp-for="TaskInfo.taskDate" class="form-control" />
                <span asp-validation-for="TaskInfo.taskDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskInfo.updateDate" class="control-label"></label>
                <input asp-for="TaskInfo.updateDate" class="form-control" />
                <span asp-validation-for="TaskInfo.updateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Calender/Pages/Delete.cshtml
@page
@model Calender.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaskInfo</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo.taskName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo.taskName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo.taskContents)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo.taskContents)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo.taskDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo.taskDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo.updateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo.updateDate)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="TaskInfo.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Calender/Pages/Details.cshtml
@page
@model Calender.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TaskInfo</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo.taskName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo.taskName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo.taskContents)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo.taskContents)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo.taskDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo.taskDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo.updateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo.updateDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.TaskInfo.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Calender/Pages/Edit.cshtml
@page
@model Calender.Pages.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TaskInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TaskInfo.ID" />
            <div class="form-group">
                <label asp-for="TaskInfo.taskName" class="control-label"></label>
                <input asp-for="TaskInfo.taskName" class="form-control" />
                <span asp-validation-for="TaskInfo.taskName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskInfo.taskContents" class="control-label"></label>
                <input asp-for="TaskInfo.taskContents" class="form-control" />
                <span asp-validation-for="TaskInfo.taskContents" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskInfo.taskDate" class="control-label"></label>
                <input asp-for="TaskInfo.taskDate" class="form-control" />
                <span asp-validation-for="TaskInfo.taskDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaskInfo.updateDate" class="control-label"></label>
                <input asp-for="TaskInfo.updateDate" class="form-control" />
                <span asp-validation-for="TaskInfo.updateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Calender/Pages/Index.cshtml
@page
@model IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Home page";
    const int MONTHROWCOUNT = 6;
    const int WEEKCOUNT = 7;
    int Count = 0;
}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>6月カレンダー</title>
</head>
<body>
    <div id="container" class="text-left">
        <h1>@Model.Message</h1>
        <form asp-page-handler="prev" method="post">
            <input type="hidden" asp-for="monthInfo.prevMonth" value=@Model.DispMonth>
            <button type="submit">前月</button>
        </form>
        <form asp-page-handler="next" method="post">
            <input type="hidden" asp-for="monthInfo.nextMonth" value=@Model.DispMonth>
            <button type="submit">後月</button>
        </form>
        <table border="1" align="center" width="50%" height="100%" class="text-center">
            <tr>
                <th><font color="red">日</font></th>
                <th>月</th>
                <th>火</th>
                <th>水</th>
                <th>木</th>
                <th>金</th>
                <th><font color="blue">土</font></th>
            </tr>
            @for (int i = 0; i < MONTHROWCOUNT; i++)
            {
            <tr>
                @for (int j = 0; j < WEEKCOUNT; j++)
            {
                @if (Model.Month[Count] != 0)
                {
                <td>
                    <form asp-page-handler="tasks" method="post">
                        <input type="hidden" asp-for="monthInfo.thisMonth" value=@Model.DispMonth>
                        <input type="hidden" asp-for="monthInfo.thisDay" value=@Model.Month[Count]>
                        <button style="background-color:white;" type="submit">@Model.Month[Count]</button>
                    </form>
                </td>
                    }
                    else
                    {
                <td></td>
                    }
                Count++;
            }
            </tr>
            }
        </table>
    </div>
</body>
</html>

Calender/Pages/TaskList.cshtml
@page
@model Calender.Pages.TaskListModel

@{
    ViewData["Title"] = "TaskList";
}

    <h1>TaskList</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TaskInfo[0].taskName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskInfo[0].taskContents)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskInfo[0].taskDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskInfo[0].updateDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.TaskInfo) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.taskName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.taskContents)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.taskDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.updateDate)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.ID">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Calender/Pages/Tasks.cshtml
@page "Tasks"
@model TasksModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Tasks";
}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
</head>
<body>
    <p>@Model.DateValue</p>
</body>
</html>
